### ISSUE TITLE
Exiting worker with exitCode=0 signalCode=null

### ISSUE THREAD

**Issue by boustanihani** [meteorhacks/cluster#20]
I managed to deploy my app after adding cluster and I set ```"CLUSTER_WORKERS_COUNT":2``` in my ```mup.json```.

My app is working fine but when I check the logs, cluster seems to be trying to initialize new workers all the time because they are exiting immediately for some reason:
```
...
Cluster: Initializing worker 55 on port 4810
Cluster: Exiting worker 55 with exitCode=0 signalCode=null
Cluster: Initializing worker 56 on port 4828
Cluster: Exiting worker 56 with exitCode=0 signalCode=null
Cluster: Initializing worker 57 on port 15815
Cluster: Exiting worker 57 with exitCode=0 signalCode=null
...
```

**Comment by arunoda** [comment]
If you are using mup try to update and do a mup setup before this.

**Comment by boustanihani** [comment]
Thanks this solved the problem :)
