### ISSUE TITLE
Displaying cluster data in client

### ISSUE THREAD

**Issue by rhyslbw** [meteorhacks/cluster#22]
I'm wanting to build a status/admin UI page to display information on the cluster (maybe even as a standalone service in the cluster). I'm firstly just wanting to list the endpoints grouped by service. I was hoping to get access to the documents via a find on `Cluster.discovery._endpointsColl`, but I see the client has a different API limited to discoverConnection. Have would you achieve this?

**Comment by arunoda** [comment]
So, you want an UI for cluster on Kadira :)
Yeah! We've plans for that. 

I don't have a ETA for that. But we'll have it.

**Comment by rhyslbw** [comment]
haha, I should have prefaced this by saying "as an interim solution ahead of support for Cluster in Kadira…"

Thinking about this more I might just put this in the backlog anyway, as Kadira is the more logical place for it. Looking forward to seeing what Kadira with Cluster support will look like!
