### ISSUE TITLE
Observe cursors

### ISSUE THREAD

**Issue by Maxpain177** [meteorhacks/cluster#25]
HI! I had a problem. When a document is added to the collection, my observers are triggered on all servers (2 clusters with 4 cores = 8 workers). How can i prevent this behavior?

For example:
~~~
Items.find().observeChanges({
  added: function(id, fields) {
    HTTP.get(fields.url, function() {
      // DO SOMETHING
    })
  }
})
~~~

Its fired on ALL workers, but i want it to only run on one worker (most are not loaded).

**Comment by arunoda** [comment]
You can use  a package like this to schedule a job on on one worker.
see: https://github.com/percolatestudio/meteor-synced-cron

**Comment by dropfen** [comment]
This actually is a perfect scenario for micro services ;)

Am 11.03.15 um 11:40 schrieb maxpain:

**Comment by arunoda** [comment]
Yes @dropfen . Another way of looking at thing.
Just deploy another Meteor app just do only that task and connect it to the cluster.

**Comment by Maxpain177** [comment]
Yes, i did so. But if I want to balance the load between the CPU cores?

**Comment by arunoda** [comment]
Run that process on a Meteor instance which uses one core. (without any
multi core stuff).
Use other three workers to the normal operation.

If you feel like that process needs more resources, allocate another core.

**Comment by Maxpain177** [comment]
Thanks!

**Comment by dropfen** [comment]
I had exactly the same issue, with some points calculation after a quiz 
ended.
Like Arunoda said, I just created one meteor instance with only Server 
code which had only the relevant code
for the Quiz.observer ,Points calculation logic and DB Connection.

Am 11.03.15 um 12:28 schrieb Arunoda Susiripala:
> Run that process on a Meteor instance which uses one core. (without any
> multi core stuff).
> Use other three workers to the normal operation.
>
> If you feel like that process needs more resources, allocate another core.
>

**Comment by arunoda** [comment]
Hope we can close this issue.

**Comment by elie222** [comment]
How do you deploy another app while still sharing code with the main app?

If you're using the same db for both apps, you'd want to share schemas too, no?
