### ISSUE TITLE
Is it possible to have multiple cores share a variable?

### ISSUE THREAD

**Issue by gbachik** [meteorhacks/cluster#26]
Hey! I'm loving all the things you guys are building for meteor!
I was using cluster up until a few days ago when I realized it breaks my current job que!

I have a custom job handler running on my server that looks like this:

```javascript
Jobs = new Mongo.Collection('jobs')

var throttle = [];
var running = false;

Meteor.setInterval(function(){
	if (!(running)) {
		running = true;
		var now = new Date();
		var time = now.getTime();
		var unfinishedJobs = Jobs.find({_id: { $nin: throttle }, date: {$lt: time} });
		unfinishedJobs.map(function (job) {
			throttle.push(job._id);
			if (job.name === 'setTime') {
				setTime(job.campaign);
			}else if (job.name === 'matchLimit') {
				matchLimitReached(job.match);
			}

			/* kill throttle */
			var index = throttle.indexOf(job._id);
			if (index > -1) {
			    throttle.splice(index, 1);
			}
			Jobs.remove({_id: job._id});
		});
		running = false;
	}
}, 500);
```

The issue is that this code gets ran on both cores... so a second one can run before the first one is completed and cause problems.

Is there a way for the separate instances to share a variable?
I want them to be able to share `var running = false;` so that way this isn't an issue!

Is this possible? 
Can I just set the environment variables to do this or?

**Comment by gbachik** [comment]
Just as a side note I `CANT` use things like synced cron because they don't run at a fast enough interval.

**Comment by dropfen** [comment]
Hmm, no it's not possible to share a variable between cores/instances 
but you could do it only over the DB.
for the cron stuff there is an package that would handle the multi 
instance issue
https://github.com/percolatestudio/meteor-synced-cron

Otherwise you could create a single operations instance, which is 
handling all the cron stuff.


Am 12.03.15 um 18:53 schrieb Gage Bachik:

**Comment by gbachik** [comment]
I'm not doing a cron, I'm running an operation in a set interval. crons are too slow I can't use them. 

How would I go about creating a single operations instance?

**Comment by dropfen** [comment]
Just create a new meteor application with the actual code in it and connect it to the same db as your main application.
As I can see you will need this function matchLimitReached in this application too.
You could then create a simple administration UI, protect it with basic auth and run it on a different subdomain or on an other port..

**Comment by gbachik** [comment]
I wont be able to do that in any easy way because that function is heavily integrated throughout multiple parts of the app </3

I guess I'll just have to drop cluster for the time being.
-Thanks

**Comment by dropfen** [comment]
However, hope you will find a good solution

**Comment by gbachik** [comment]
Thanks a bunch!
Do you think something like this would work?
```javascript
var throttle = [];

Meteor.setInterval(function(){
	var running = Running.findOne({});
	if (running) {
		if (!(running.isRunning)) {
			Running.update({
				_id: running._id
			}, {
				$set: {
					isRunning: true
				}
			});
			var now = new Date();
			var time = now.getTime();
			var unfinishedJobs = Jobs.find({_id: { $nin: throttle }, date: {$lt: time} });
			unfinishedJobs.map(function (job) {
				throttle.push(job._id);
				if (job.name === 'setTime') {
					setTime(job.campaign);
				}else if (job.name === 'matchLimit') {
					matchLimitReached(job.match);
				}

				/* kill throttle */
				var index = throttle.indexOf(job._id);
				if (index > -1) {
				    throttle.splice(index, 1);
				}
				Jobs.remove({_id: job._id});
			});
			Running.update({
				_id: running._id
			}, {
				$set: {
					isRunning: false
				}
			});
		}
	}
}, 100);
```

**Comment by gbachik** [comment]
basically I'm just getting and setting something in the database...

but this seems dangerous...
I'm updating a collection every 100ms...

Is this kind of load really bad on mongo?

**Comment by arunoda** [comment]
So, now you need to think a bit.

1) I hope you can run this only on one instance. What don't you do that
2) Try to create a one separate app and do it
3) Normally, you should avoid on sharing varibales between cores or something. That's never going to scale
4) I think, for your job, that's okay. You don't need to scale it, just run it on a one spearete instance(app)

**Comment by rhyslbw** [comment]
Running through Mongo should be fine for most cases, but no need to roll your own solution. Have you seen [vsivsi:job-collection](https://github.com/vsivsi/meteor-job-collection) ? There's a 1.0.0 release candidate out now, so it's as good as production ready. It provides many configuration options on how to manage the queue and workers.

I'm configuring a queue in a server-only app, and will be running a dedicated Mongo database just for the queue management

**Comment by dropfen** [comment]
Don’t know, but honestly it doesn’t look good for me. This will definitely produce some problems and the update steps will cost performance without guaranties for that, what you are expecting.
If the logic inside of matchLimitReached(match) is only related to Server/DB, separate it from the production WEB code itself and run it in a single instance.
Don’t know what you are trying to do, but I think it could be done somehow else, easier. Sleep and look tomorrow on it again, this definitely helps ;)

**Comment by gbachik** [comment]
Yeh I'll just use a mongo collection to tell it to only run on one instance.
I can use job-collection because its too slow.

I need to run this function every 100ms unless its already running.
Thanks for the help guys

**Comment by rhyslbw** [comment]
You can define the pollInterval to be any value with [processJobs](https://github.com/vsivsi/meteor-job-collection/tree/dev#jq--jcprocessjobstype-options-worker---anywhere), although with the [new version](https://github.com/vsivsi/meteor-job-collection/tree/dev) you can configure an [observer-based worker](https://github.com/vsivsi/meteor-job-collection/tree/dev#externally-trigger-the-jobqueue-to-seek-new-work), which would be ideal for your use-case I believe.

**Comment by arunoda** [comment]
Hope we can close this issue.
But, we can carry the discussion forward.
