### ISSUE TITLE
Firefox Block CORS/XHR

### ISSUE THREAD

**Issue by jadsonlourenco** [meteorhacks/cluster#28]
So, I have two systems: **backend.site.com** and **client.site.com**
But in Firefox the **Cross-Origin** blocks the content of the *backend*. I configured the package *browser-policy* but the error continues.

But I can't see this error in: https://bulletproofmeteor.com/
@arunoda What did you do to resolve this?

PS: I'm sorry to open this issue, but after hours trying and searching was not a solution, so I have to ask for those who already have it resolved. Thank You!

**Comment by arunoda** [comment]
Normally, meteor's sockjs requests are configured for cross domain stuff.
Nothing much to do.
Can I see some live version I can check for?

**Comment by jadsonlourenco** [comment]
You can see the live version: https://beta-new.chessboardradio.com/ - https://backend.chessboardradio.com/
or the apps code?

I'm using the same example that you talk on documentation, with DigitalOcean server and CloudFlare (SSL, with DISABLE_WEBSOCKETS="1").
But I get the same error on localhost.

**Comment by arunoda** [comment]
May be that's because BFM uses a root domain.
I'll give it a try .

**Comment by jadsonlourenco** [comment]
sorry, "BFM"?

**Comment by arunoda** [comment]
My Bad. It's should be BPM (BulletProof Meteor)

**Comment by arunoda** [comment]
I use cluster for Kadira as well. But, I directly use WS directly.

**Comment by jadsonlourenco** [comment]
Yes, I try with enabled WS on localhost, for example, and not work too. 

But in BFM you have two sub domain, that I think are "clients" of cluster. Or thinking better, your backend and front-end apps are the same app, just with more "nodes" to make the cluster to load balance, is that?

Well, for my plan I think to make one backend system, just with server code, and other just with client code, so the "clients" will ever call to backend to get/post content from database. Then the backend system will have more instances to load balance the server side job, if need.

And this works fine on Chrome, but not in Safari, Firefox and Opera. All the same error.

**Comment by jadsonlourenco** [comment]
ok, I not will close this now because I want share the solution soon, but in this case I'm working with Polymer (Web Components) and on Firefox I can't load the view. So I removed the polymer from ```<head>```and now I can see the content from the **backend** of the Cluster. I get this message on Firefox console, but now I know that backend send data to "client", and cluster works on Firefox too.

Now I need to know why I get this message yet on console, and ever say the "Cross-Origin" is a problem with backend URL...

Well, thanks for you help, I will continue and soon back with solution.

**Comment by arunoda** [comment]
Okay. Cool.
I will give it a look also.

**Comment by jadsonlourenco** [comment]
Ok, closing here because I get the solution.

**On console of Firefox ever show this message, but load the content correctly.**

I get a problem with Polymer, because of **webcomponents.js** need be loaded before the render the main template, so I have added it as a package to load on start, inside Meteor app, not from CDN like before.

Well, thank you so much for the reply, and help.

**Comment by arunoda** [comment]
Okay. Great. Happy to help.
