### ISSUE TITLE
service's name caused an error on client

### ISSUE THREAD

**Issue by darkship** [meteorhacks/cluster#34]
Hello,

I tried this in my repo (https://github.com/darkship/test_cluster_client_error) :

```
if (Meteor.isServer) {
      Cluster.connect("mongodb://localhost:27017/discovery");
      Cluster.register("test-test");
}
```

But on the client I have an error (that was not expected and killed other connexions):

```
 Firefox could not connect to ws://localhost:5001/cluster-ddp/8d6a5062c883e6d079209864a3fbeec534018d1e/test-test/866/10ypgijw/websocket.
```

And sometimes on the server too :

```
Cluster: no such endpoint for service:test-test
```

Replacing <code>test-test</code> by <code>test</code> solved the issue.
I tried with <code>test_test</code> and it didn't work either.So what are the service's name limitations ?

**Comment by davidyaha** [comment]
:+1:
