### ISSUE TITLE
Update Cloudflare websocket info

### ISSUE THREAD

**Issue by lorensr** [meteorhacks/cluster#35]
Readme says:

`We turn off WebSockets since cloudflare does not support SSL with WebSockets yet!`

They support both ws:// and wss:// if you have an enterprise account.

**Comment by arunoda** [comment]
Yes they do. But it costs $5000 per month. Hope no one in the meteor
community will get a setup like that yet.

**Comment by arunoda** [comment]
Hope we can close this.

**Comment by jadsonlourenco** [comment]
Soon will support WS for free, like SSL, just follow Cloud Flare blog for updates...

**Comment by arunoda** [comment]
Yeah! They will. 
I talked to them. They don't have plans for general availability yet. (even for paid plans other than enterprise)
Hope, they can do it soon. It will simplify a lot of things.

**Comment by lorensr** [comment]
Thanks for the info. Switching my domain off them for now because I want to
use websockets.

**Comment by lorensr** [comment]
Oh, I just found this:

https://meteorhacks.com/cloudflare-meets-meteor.html

Does cluster support Option 2?

`export DDP_DEFAULT_CONNECTION_URL=http://ddp.yourdomain.com`

**Comment by arunoda** [comment]
Yes it is. But, if you are using SSL with CF, you need to make sure this connection is also SSL supported.
