### ISSUE TITLE
Question: Cordova support 

### ISSUE THREAD

**Issue by boustanihani** [meteorhacks/cluster#5]
Does **meteorhacks:cluster** support **cordova meteor builds** ?

**Comment by arunoda** [comment]
Yes. it does.
This is based on DDP and it will work without any issues.

**Comment by boustanihani** [comment]
Is there any special config needed when building ? (regarding the **--server** param)
```meteor build <bundle path> --server <host>:<port>```
https://github.com/meteor/meteor/wiki/Meteor-Cordova-Phonegap-integration#building

**Comment by arunoda** [comment]
No. simply use the whatever you've used previously.

**Comment by boustanihani** [comment]
Thanks :+1:

**Comment by arunoda** [comment]
Great. Let me know how it worked.

**Comment by boustanihani** [comment]
I will :)
