### ISSUE TITLE
Question: Is there a way in app that we can detect current running core?

### ISSUE THREAD

**Issue by vuhpham** [meteorhacks/cluster#51]
I'm running to an issue that I have an Mongo update query in startup code of server:
```
if (Meteor.isServer) {
 Meteor.startup(function(){
    Posts.find().observeChanges({
        added: function(id, fields) {
            Authors.update({_id: fields.authorId}, {$inc: {count: 1}});
        }
    })
 });
}
```
I run app with 4 cores server and this added event run 4 times which I expected just 1. 
Is there a way in app that we can detect current running core? Or any other best practices to run observerChanges in multicore environment?

**Comment by arunoda** [comment]
It's very tricky to run these kind of stuff. This is not only for cores,
think what will be happen when you are running multiple servers of your app.

Here's a way to to that.

* Inside every worker there's a env variable called `CLUSTER_WORKER_ID`.
Try to create the observer when there is no such worker
* When you are running multiple servers, expose a new env for only one
server. And check for that env as well.
* So, this observer runs on a single server and single core.

You can even look at some other stuffs like, doing these things as a job
queue or running different app.

**Comment by vuhpham** [comment]
Thanks @arunoda  I think I'd better run this in a microservice then.
However that env variable is nice as well. :+1:
