### ISSUE TITLE
Client connection IP is reported as 127.0.0.1

### ISSUE THREAD

**Issue by lorensr** [meteorhacks/cluster#54]
Is this something `cluster` and/or `mup` is doing, or is it a problem with some other package?

```
Accounts.onLogin (info) ->
  console.log('onLogin', info.connection.clientAddress)
  console.log(info.connection.httpHeaders)
```

```
[parlay.io] onLogin 127.0.0.1[parlay.io] 
[parlay.io] { host: 'parlay.io',[parlay.io] 
[parlay.io]   'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36',[parlay.io] 
[parlay.io]   'accept-language': 'en-US,en;q=0.8' }[parlay.io]
```

**Comment by arunoda** [comment]
Are you using mup SSL?

**Comment by lorensr** [comment]
Yes

On Thu, May 7, 2015 at 1:20 AM, Arunoda Susiripala <notifications@github.com

**Comment by arunoda** [comment]
That's the issue. Since its a SSL terminator it does not write headers.

Check the mupx branch of mup. We have a solution.

**Comment by lorensr** [comment]
Thank you, I look forward to it being stable and merged into mup.

**Comment by arunoda** [comment]
Okay. Sure.

**Comment by lorensr** [comment]
FYI with Galaxy, `info.connection.httpHeaders['x-forwarded-for']` is filled in, and the value is used for `info.connection.clientAddress`
