### ISSUE TITLE
Cluster and timers

### ISSUE THREAD

**Issue by ofqwx** [meteorhacks/cluster#57]
Hi!,
We are developing a meteor app and using the cluster package.
We are currently having issues with the meteor timers (Meteor.setInterval and Meteor.clearTimeout); only the instance that started the timer is able to clear it, so if you are working with 4 instances the operation only success 25% of the times.

Is there any way of synchronize the timers with the application instances?

**Comment by arunoda** [comment]
Having distributed timers is hard. Try to use synced-cron project. See: https://github.com/percolatestudio/meteor-synced-cron
