### ISSUE TITLE
Multi-core support question

### ISSUE THREAD

**Issue by ffxsam** [meteorhacks/cluster#58]
Hi guys,

Quick question. Simply by adding the `meteorhacks:cluster` package and setting the env var `CLUSTER_WORKERS_COUNT` to `auto`, does this make any difference for a Meteor app running a single instance on a single host? Does it enable multi-core support and/or improve performance? Or is the cluster package only useful for multiple instances?

**Comment by arunoda** [comment]
This is useful if you are running on a multi-core machine.
Running on a single core machine, doesn't make any different.

**Comment by ffxsam** [comment]
Ok, so even if I'm using a single instance/single server, it still helps?

**Comment by arunoda** [comment]
Nope. You need to have a multi-core server.

**Comment by ffxsam** [comment]
I think we're having a misunderstanding.  What I'm asking is:

If I have a multi-core server, but running only a single instance of Meteor & Mongo (no cluster), will using the cluster package and setting `CLUSTER_WORKERS_COUNT` to `auto` still help performance? Or do I need to be running multiple Meteor/Mongo instances?

**Comment by arunoda** [comment]
Ah, now I got it.
Yes it is. You only need to run only one instance.
Behind the scene, cluster will spawn new instances and do the necessary
communication between them.

**Comment by ffxsam** [comment]
Thanks Arunoda! Makes sense.

**Comment by ffxsam** [comment]
@arunoda Oh, I had one more question:

cluster will automatically spawn extra instances as needed, correct? How does that work? Do those instances take up additional port numbers? (3001, 3002, etc)

**Comment by arunoda** [comment]
Yes they are.

**Comment by ffxsam** [comment]
Sorry for all the questions.

So if I want to run a few Meteor apps on one server, how can I ensure extra instances of app1 won't collide with ports for app2? How many instances are typically spawned? Should app1 be on port 3000, app2 on port 3100? (or 4000)

If all these details are covered somewhere, let me know.

**Comment by arunoda** [comment]
We use a npm module called portscanner to find the port:
https://www.npmjs.com/package/portscanner

**Comment by ffxsam** [comment]
Ah! So I don't have to worry about port collisions.

Thanks again :) And awesome work on mup and cluster!! These are fantastic tools.
