### ISSUE TITLE
Too much db connexions

### ISSUE THREAD

**Issue by darkship** [meteorhacks/cluster#62]
I'm not sure that I have to post this issue here or on Meteor.

If I have understand, a single worker opens 
- a connection to each member of the replicaSet for oplog defined in MONGO_OPLOG_URL (=A)
- a connection to the primary  MONGO_URL

And the members of the replicaSet are interconnected. (=B)

On compose.io, I have a replicaSet of 1 primary,2 secondary, 1 ARBITER (B=3)and the Replica Set URI has 2 DBs (A=2).
- CLUSTER_WORKERS_COUNT = x : (x+1)*(1+A)+B connections
- CLUSTER_WORKERS_COUNT = 0 : (1+2)+3=6 connections
- CLUSTER_WORKERS_COUNT = 1 : 2*(1+2)+3=9 connections

How comes that with 2 app instances, the first with  <code>CLUSTER_WORKERS_COUNT=3</code> and the second  <code>CLUSTER_WORKERS_COUNT=12</code>, I can have nearly 3000 connections ?

I'm using forever to start/restart/stop. Could it be that using forever doesn't close connections   ?

**Comment by arunoda** [comment]
node-mongodb driver maintains connections for you. So, actual connection count may exceed 9 per app. But having 3000 is crazy. 

Forever can be an issue. Frankly I didn't test for that scenario. Could you the workers process.
And try to use `netstat` see who is holding connections.

**Comment by darkship** [comment]
This is my netstat line count after rebooting my app this morning: 
<code>netstat |grep "compose_secondary_ip" -c  =>1939</code>
<code>netstat |grep "compose_primary_ip" -c => 2148</code>
 
And compose shows 2210 on compose_primary and 1992 compose_secondary_ip

(Note : I dropped the app instance with 3 workers.)
