### ISSUE TITLE
Launch multiple instances of the application on a multi-core server with cluster and meteor-up

### ISSUE THREAD

**Issue by MaazAli** [meteorhacks/cluster#8]
Is there a way to be able to launch multiple instances of the application on the same server that has multiple cores with meteor-up and utilize cluster to load balance? If so, how should this be setup?

**Comment by arunoda** [comment]
Theoretically, it's possible. But I am working on better way by just
installing a package :)

Or cluster will have it natively. Stay tuned!

**Comment by MaazAli** [comment]
> But I am working on better way by just
installing a package :)
> Or cluster will have it natively. Stay tuned!

Awesome, can't wait! Good work on cluster by the way.

**Comment by boustanihani** [comment]
:+1:

**Comment by rhyslbw** [comment]
Nice nice nice

**Comment by eportico** [comment]
Molaaaaaaa !!! @arunoda great work!
I'm also looking for the best way to launch multiples meteor instances on multicore machine.
I wait,
very thanks for you work

**Comment by arunoda** [comment]
We could do this before end of this month. Now I am working on performance
improvements.

**Comment by rclai** [comment]
This.. is so awesome!

**Comment by Sewdn** [comment]
+1

**Comment by smeijer** [comment]
Can't wait :)

**Comment by arunoda** [comment]
Started working on this: https://github.com/meteorhacks/cluster/tree/multi-core

**Comment by arunoda** [comment]
All is done. Will do the release tomorrow with the performance test.

**Comment by arunoda** [comment]
Hope we can close this issue: https://meteorhacks.com/introducing-multi-core-support-for-meteor.html

**Comment by MaazAli** [comment]
Awesome, i'll close the issue and test this later today. Great work.

**Comment by rclai** [comment]
@arunoda is it possible for this multi-core functionality to be on its own package? I think some people might not want to create multiple instances but only want to use multiple cores. Is that possible?

**Comment by arunoda** [comment]
@rclai That's not impossible. But, then I had to duplicate some code. That's why I put this into the cluster. 
Anyway, you don't need to create multiple instances. Just use `cluster` without invoking any multi server stuff.

see: https://github.com/meteorhacks/cluster#multi-core-support

**Comment by dnish** [comment]
@arunoda I'm using <code>chfritz:easycron</code> to run some cronjobs in my Meteor application. Will it run multiple times, because there are multiple instances running, if yes, how can I decide between each instance? Normally, I would add a single environment variable for each instance, and check the cronjob script against it (f.e. only run cronjob if it is instance 1) -  but that doesn't work if the instances are running on the same server.

**Comment by ghost** [comment]
@dnish yes it will run multiple timers.. if you want to scale, the first step is to separate your application into smaller parts, that will make scaling up your app much easier... either with the cluster package or some other tools/technologies...
